language: node_js

node_js:
  - "6"
  - "8"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install --build-from-source

notifications:
  email: false

deploy:
  provider: script
  script: npm run pre-gyp-release
  skip_cleanup: true
  on:
    # Deploys happen for all tagged releases
    tags: true
    repo: resin-io/node-ext2fs