language: node_js

os:
  - linux
  - osx

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48; fi
  - npm install --build-from-source

notifications:
  email: false

deploy:
  provider: script
  script: npm run pre-gyp-release
  skip_cleanup: true
  on:
    # Deploys happen for all tagged releases
    tags: true
    repo: resin-io/node-ext2fs